services:
  wayback_machine_downloader:
    build:
        context: .
    tty: true
    image: wayback_machine_downloader:latest
    container_name: wayback_machine_downloader
    environment:
      - ENVIRONMENT=${DEVELOPMENT:-production}
      - OPTIONS=${OPTIONS:-""}
      - TARGET_URL=${TARGET_URL}
    env_file:
      - ./.env
    volumes:
      - ./db/mysql_client.cnf:/etc/my.cnf:ro
      - ./db/migrations:/build/db/migrations:rw
      - .:/build:rw
      - ./websites:/websites:rw
    command: /build/bin/wayback_machine_downloader ${TARGET_URL} ${OPTIONS}