FROM ruby:3.4.4-alpine
USER root

# Necessary packages for Nokogiri & mysql2 gems
RUN apk add --no-cache \
  build-base \
  libxml2-dev \
  libxslt-dev \
  tzdata \
  mariadb-dev \
  mariadb-client
  
WORKDIR /build

COPY Gemfile /build/
COPY *.gemspec /build/

RUN bundle config set jobs "$(nproc)" \
    && bundle install

COPY . /build

ENTRYPOINT [ "/build/bin/wayback_machine_downloader", "--directory", "/build/websites" ]
